decks: 
  - Greek::Croy_0[1-9]
  - Greek::Croy_1[0-4]
  - Greek::Metzger_10x

model: 
  repo: ilsp/Llama-Krikri-8B-Instruct-GGUF
  file: "*q4_k_m.gguf"

output:
  dialect: Koine Greek
  length: 0.5

forms:
  - present imperative
  - present participle
  - present infinitive
  - present active indicative
  - present middle indicative
  - present passive indicative
  - imperfect active indicative
  - imperfect middle indicative
  - imperfect passive indicative
  - aorist imperative
  - aorist participle
  - aorist infinitive
  - aorist active indicative
  - aorist middle indicative
  - aorist passive indicative
  - future infinitive
  - future active indicative
  - future middle indicative
  - future passive indicative
